# Generated by Django 5.1.7 on 2025-03-19 22:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_location", models.CharField(max_length=255)),
                ("pickup_location", models.CharField(max_length=255)),
                ("dropoff_location", models.CharField(max_length=255)),
                ("start_time", models.DateTimeField()),
                ("current_cycle_hours_used", models.FloatField()),
                ("distance_miles", models.FloatField()),
                ("duration_hours", models.FloatField()),
                ("route_data", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="ELDLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("timespent", models.FloatField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OFF_DUTY", "OFF_DUTY"),
                            ("SLEEPER_BERTH", "SLEEPER_BERTH"),
                            ("DRIVING", "DRIVING"),
                            ("ON_DUTY", "ON_DUTY"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("PRE_CHECK", "PRE_CHECK"),
                            ("DRIVING", "DRIVING"),
                            ("PICKUP", "PICKUP"),
                            ("BREAK", "BREAK"),
                            ("FUEL_STOP", "FUEL_STOP"),
                            ("OFF_DAYS", "OFF_DAYS"),
                            ("DROP_OFF", "DROP_OFF"),
                            ("DONE", "DONE"),
                        ],
                        max_length=255,
                    ),
                ),
                ("coordinates", models.JSONField()),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eld_logs",
                        to="trips.trip",
                    ),
                ),
            ],
        ),
    ]
